### ISSUE TITLE
17sept 2013 build v10.2 - Keyboard not working for defy plus

### ISSUE THREAD

**Issue by jayant221** [Quarx2k/jordan-kernel#10]
Jordan/DefyPlus keyboard appears and disappears immediately. Keyboard is not working.
Build: 10.2
Date: 17th Sept 2013
Fone Model: Defy Plus / Jordan

Thanks

**Comment by Blechd0se** [comment]
I recommend wipe /data. This isn't related to the kernel anyway, so i am closing this…
