### ISSUE TITLE
Unable to compile the kernel

### ISSUE THREAD

**Issue by silverdragon727** [Quarx2k/jordan-kernel#11]
I did follow [Kayant's guide](http://forum.xda-developers.com/showthread.php?t=2040135) to compile the kernel, but it failed immediately and gave the following output:

```
#
# configuration written to .config
#
/bin/sh: 1: /home/jhk/AeroKernel/scripts/dtc/dtc: not found
```

I know the problem is related to the Device Tree Compiler, but how to build it is out of my knowledge. How can I deal with this?

**Comment by silverdragon727** [comment]
@Blechd0se Could you give me some advice?

**Comment by Quarx2k** [comment]
Disable CONFIG_DTC in defconfig:)

2014-02-17 15:37 GMT+07:00 jhk001 notifications@github.com:

**Comment by silverdragon727** [comment]
Thanks :)
