### ISSUE TITLE
CONFIG_IPV6_PRIVACY

### ISSUE THREAD

**Issue by charlie2alpha** [Quarx2k/jordan-kernel#8]
Having CONFIG_IPV6_PRIVACY=y causes problems with the Google Messaging service. The service mistakenly uses a temporary IPv6 address to establish a link to the Google servers, using it for push notifications and sync. The temporary address however becomes invalid after a very short period of time, causing the connection to fail. The service tries to connect again, and again, in an endless loop.

Ideally, this should be fixed in the Google code, to use a normal IPv6 outbound address, but this is closed source Google code.

As a workaround I propose that CONFIG_IPV6_PRIVACY is set to "N" (CONFIG_IPV6_PRIVACY=n) so we can avoid such issues, this will force the system to always use the normal IPv6 address and not a temporary address.

**Comment by charlie2alpha** [comment]
The build that @Kayant made to test the RIL issues has the https://github.com/Quarx2k/jordan-kernel/commit/4e6c6fea8c57e1200e7321054943be39be7abaca commit included, which disables the IPv6 temporary addresses. Push notifications work again correctly with IPv6,

Interesting thing to note, my Nexus 7 tablet has CONFIG_IPV6_PRIVACY=y, but has no problem with the notifications. We cannot know though what Google has done with the code there, it's safer to keep it disabled for the DEFY.

Since this is now working, I am closing the issue.

**Comment by Quarx2k** [comment]
Nexus7 use 3.x kernel, updated Netfilter. That's why no problems.
